.TH IFIND "1" "2018-04-25" "iRODS find utility" "User Commands"

.SH NAME
ifind \- iRODS find utility

.SH SYNOPSYS
.B ifind
.B [ \-h ]
.B [ \-C\ \fIconnection\fR ]
.B [ \-D ]
.B [ \-E\ \fIresource\fR ]
.B [ \-X\ \fIregexp\fR ]
.B [ \-Y\ \fIsubst\fR ]
.B [ \-b\ \fIbatchsize\fR ]
.B [ \-c\ \fIcommand\fR ]
.B [ \-d\ \fIlevel\fR ]
.B [ \-f ]
.B [ \-n\ \fIn\fR ]
.B [ \-p\ \fIn\fR ]
.B [ \-q ]
.B [ \-R \fIn,w,m\fR ]
.B [ \-s\ \fItype\fR ]
.B [ \-S ]
.B [ \-v ]
.B \fIcollection\fR

.SH DESCRIPTION

This utility is a bit similar to the traditional \fIfind\fR
command in Unix.

It scans a directory tree and executes a command for each
file passing the file/directory name as an argument.

To list the directory tree it directly connects to the Postgres
database with the metadata so it's best to be used on the
icat host though it can take any connect string to connect
to a remote Postgres database. It is Postgres specific. It uses
cursors so it retrieves the results in batches, how many rows
to return in a batch is adjustable. It can be directed to scan
only directories or files, the full pathname is returned in
every case. The output can be sorted, reverse sort for directories
produces a canonical order traverse list finishing with the top level.

.TP
.B \-h\fR
to print this help.

.TP
.B \-C \fIconnection\fR
Postgres connect string to identify the database to connect to.
Use quotes when it contains spaces.

.TP
.B \-D\fR
Print directory names (collections) only. The default is to print file names.

.TP
.B \-E \fIresource\fR
Resource name to select.

.TP
.B \-X \fIregexp\fR
Select files or directories with matching POSIX regexp pattern.

.TP
.B \-Y \fIregexp\fR
Substitute regexp match with this string.

.TP
.B \-b \fIbatchsize\fR
the number of rows to retrieve from the metadata database in one batch.
The default is 1024.

.TP
.B \-c \fIcommand\fR
is the command to execute for each file/directory.
The absolute pathname will be appended in single quotes.
Alternatively a printf string with '%s' markers can be
supplied, in which case the markers will be replaced with
the pathname, just like with printf. Only four of these can
be specified. It is best to supply this string using single
quotes around the %s since it might contain spaces.
The default is to print the full pathname, in this case
multitasking is not allowed since it would result in garbled
output.

.TP
.B \-d \fIlevel\fR
is the debug level, larger number for more details.
The default is no debug, if this switch is omitted.

.TP
.B \-f\fR
Force, continue even when the command returns non-zero status.

.TP
.B \-n \fIn\fR
This option specifies multitasking, n tasks will be forked in
parallel, each to process one batch as moving forward. Please note
that in this case the output with pathnames will be garbled and not
suitable for further processing since the all the processes are writing
the same time.

.TP
.B \-p \fIn\fR
progress indicator, print a dot for every \fIn\fR database fetch as processed.
One fetch returns \fIbatchsize\fR records, sometimes less at the end so it is
approximate.

.TP
.B \-q\fR
Quiet.

.TP
.B \-r \fIn\fR
Replica number. The default is all replicas.

.TP
.B \-R \fIn,w,m\fR
Retry failed command \fIn\fR times after waiting for \fIw\fR seconds,
allowed \fIm\fR max tries all in all.

.TP
.B \-s \fItype\fR
Sort type, 0 for no sort, 1 for ascending, 2 for descending,
3 for ascending unique, 4 for descending unique. (Note that
files with replicas are returned as multiple rows.)

.TP
.B \-S\fR
Print summary at the end. The transfer speed numbers can be
meaningless in case the executed command deals only with
metadata and not doing any actual data movement.

.TP
.B \-t\fR
Test, print command string but don't execute.

.TP
.B \-u \fIlocale\fR
Check pathnames if they confirm to UTF-8 or other locale, as specified.
The locale name is the one like en_US.UTF8 as per the Posix specification.

.TP
.B \-v\fR
Verbose. Print the names.

.TP
.B \fIcollection\fR
is a collection/directory to use as root of the tree. It should be
absolute pathname.

.SH EXAMPLES

.B ifind -v /snic.se/home
will list all files under the specified directory.

.B ifind -c 'ils -L' /snic.se/home
to create a full attribute list of all files.

The command 
.B ifind -D -v -s 2 /snic.se/home
will list all directories under home in reverse canonical order,
finishing with the top level directory. This is suitable for example
to delete a directory tree.

To rename all files in a directory tree to have a prefix x_ you can use
the command
.B ifind -c \(dqimv '%s' 'x_%s'\(dq /snic.se/home/user00
It might be a good idea to single quote the file names in case they include
spaces.

Note that quotes in file names are not allowed and will cause an error
message to be displayed.


